### ISSUE TITLE
RuntimeError: torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by Autumn-Whisper** [OpenMOSE/RWKV5-LM-LoRA#1]

**Comment by OpenMOSE** [comment]
give more info

**Comment by Autumn-Whisper** [comment]
I just use the autodl(a cloud server provider ) to train the rwkv5-3b
The environment is work normally for RWKV-LM-Lora to train the RWKV-4-Raven
The others(besides the dataset) are all use default setting

**Comment by OpenMOSE** [comment]
okay. give me more details about traceback.
binidx dataset right?

**Comment by Autumn-Whisper** [comment]
I use the make_data.py to change the jsonl to binidx. I only chang the "demo.jsonl" to "train.jsonl". And not change any others

**Comment by Autumn-Whisper** [comment]
I have tried 3 kind of GPU: A100, RTX3090, RTX4090

**Comment by OpenMOSE** [comment]
you try lora setting like this?

--lora_parts=att,ffn,time,ln

**Comment by Autumn-Whisper** [comment]
--lora_parts=ffn
I  only train the ffn

**Comment by OpenMOSE** [comment]
If you want ffn train, try rwkv5-lm- lora lion in experiment folder.

On train bash
--lora_parts = att,ffn,ln,ffn_r,ffn_k,ffn_v

Currently need att,ffn,ln for training
Also you can choose merge value on merge_chaos.py

**Comment by Autumn-Whisper** [comment]
Thank you! I will have a try

**Comment by OpenMOSE** [comment]
why you try training only ffn? do you have any reasons?
